package com.revature.models;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Component
@Entity
@Table(name="forums")
public class Forums implements Serializable, IForums {


	private static final long serialVersionUID = -8064198802059695364L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="forums_id")
	private long forumsid;
	
	@Column(name="forums_topic")
	private String forumstopic;
	
	@Column(name="forums_comment")
	private String forumscomment;
	
	@ManyToOne
	@JoinColumn(name="forums_user")
	private User user;

	@Override
	public User getUser() {
		return user;
	}

	@Override
	public void setUser(User user) {
		this.user = user;
	}

	// Generated by Source menu - empty constructor for jackson
	public Forums() {
		super();
	}
	
	// Generated by Source menu - standard Constructor
	public Forums(long forumsid, String forumstopic, String forumscomment, User user) {
		super();
		this.forumsid = forumsid;
		this.forumstopic = forumstopic;
		this.forumscomment = forumscomment;
		this.user = user;
	}

	// Generated by Source menu - Getters and Setters
	@Override
	public long getForumsid() {
		return forumsid;
	}

	@Override
	public void setForumsid(long forumsid) {
		this.forumsid = forumsid;
	}

	@Override
	public String getForumstopic() {
		return forumstopic;
	}

	@Override
	public void setForumstopic(String forumstopic) {
		this.forumstopic = forumstopic;
	}

	@Override
	public String getForumscomment() {
		return forumscomment;
	}

	@Override
	public void setForumscomment(String forumscomment) {
		this.forumscomment = forumscomment;
	}

	@Override
	public int hashCode() {
		return Objects.hash(forumscomment, forumsid, forumstopic);
	}

	// Generated by Source menu - hashCode and equals
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Forums other = (Forums) obj;
		return Objects.equals(forumscomment, other.forumscomment) && forumsid == other.forumsid
				&& Objects.equals(forumstopic, other.forumstopic);
	}

	// Generated by Source menu - toString()
	@Override
	public String toString() {
		return "Forums [forumsid=" + forumsid + ", forumstopic=" + forumstopic + ", forumscomment=" + forumscomment
				+ "]";
	}
	
//class closed	
}