package com.revature.models;

public interface IForums {

	IUser getUser();

	void setUser(User user);

	// Generated by Source menu - Getters and Setters
	int getForumsid();

	void setForumsid(int forumsid);

	String getForumstopic();

	void setForumstopic(String forumstopic);

	String getForumscomment();

	void setForumscomment(String forumscomment);

	int hashCode();

	// Generated by Source menu - hashCode and equals
	boolean equals(Object obj);

	// Generated by Source menu - toString()
	String toString();

}
