package com.revature.models;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.stereotype.Component;


@Component
@Entity
@Table(name="portfolios")
public class Portfolios implements Serializable {


	private static final long serialVersionUID = -195234255365846115L;

	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="portfolio_id")
	private long portfolioid;
	
	@ManyToOne
	@JoinColumn(name ="portfolio_user")
	private User user;

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	// Generated by Source menu - empty constructor for jackson	
	public Portfolios() {
		super();
	}

	// Generated by Source menu - standard Constructor
	public Portfolios(long portfolioid, User user) {
		super();
		this.portfolioid = portfolioid;
		this.user = user;
	}

	// Generated by Source menu - Getters and Setters
	public long getPortfolioid() {
		return portfolioid;
	}

	public void setPortfolioid(long portfolioid) {
		this.portfolioid = portfolioid;
	
	}
	
	// Generated by Source menu - hashCode and equals
	@Override
	public int hashCode() {
		return Objects.hash(portfolioid, user);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Portfolios other = (Portfolios) obj;
		return portfolioid == other.portfolioid && Objects.equals(user, other.user);
	}

	// Generated by Source menu - toString()
	@Override
	public String toString() {
		return "Portfolios [portfolioid=" + portfolioid + ", user=" + user + "]";
	}
	
	
	
//class closed	
}
