package com.revature.models;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


@Component
@Entity
@Table(name="users")
public class User implements Serializable, IUser {


	private static final long serialVersionUID = -4553508689874995351L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="user_id")
	private int userid;
	
	@Column(name="user_lastname")
	private String userlastname;
	
	
	@Column(name="user_firstname")
	private String userfirstname;
	
	@Column(name="user_email")
	private String useremail;
	
	@Column(name="user_password")
	private String userpassword;
	
	@Column(name="user_streetaddress")
	private String userstreetaddress;
	
	@Column(name="user_city")
	private String usercity;
	
	@Column(name="user_state")
	private String userstate;
	
	
	// Generated by Source menu - empty constructor for jackson
	public User() {
		super();
	}
	
	public User(int userid, String userlastname, String userfirstname, String useremail, String userpassword,
			String userstreetaddress, String usercity, String userstate) {
		super();
		this.userid = userid;
		this.userlastname = userlastname;
		this.userfirstname = userfirstname;
		this.useremail = useremail;
		this.userpassword = userpassword;
		this.userstreetaddress = userstreetaddress;
		this.usercity = usercity;
		this.userstate = userstate;
	}

	@Override
	public int getUserid() {
		return userid;
	}

	@Override
	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Override
	public String getUserlastname() {
		return userlastname;
	}

	@Override
	public void setUserlastname(String userlastname) {
		this.userlastname = userlastname;
	}

	@Override
	public String getUserfirstname() {
		return userfirstname;
	}

	@Override
	public void setUserfirstname(String userfirstname) {
		this.userfirstname = userfirstname;
	}

	@Override
	public String getUseremail() {
		return useremail;
	}

	@Override
	public void setUseremail(String useremail) {
		this.useremail = useremail;
	}

	@Override
	public String getUserpassword() {
		return userpassword;
	}

	@Override
	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	@Override
	public String getUserstreetaddress() {
		return userstreetaddress;
	}

	@Override
	public void setUserstreetaddress(String userstreetaddress) {
		this.userstreetaddress = userstreetaddress;
	}

	@Override
	public String getUsercity() {
		return usercity;
	}

	@Override
	public void setUsercity(String usercity) {
		this.usercity = usercity;
	}

	@Override
	public String getUserstate() {
		return userstate;
	}

	@Override
	public void setUserstate(String userstate) {
		this.userstate = userstate;
	}


	@Override
	public int hashCode() {
		return Objects.hash(usercity, useremail, userfirstname, userid, userlastname, userpassword,
				userstate, userstreetaddress);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		return  Objects.equals(usercity, other.usercity) && Objects.equals(useremail, other.useremail)
				&& Objects.equals(userfirstname, other.userfirstname) && userid == other.userid
				&& Objects.equals(userlastname, other.userlastname) && Objects.equals(userpassword, other.userpassword)
				&& Objects.equals(userstate, other.userstate)
				&& Objects.equals(userstreetaddress, other.userstreetaddress);
	}

	@Override
	public String toString() {
		return "User [userid=" + userid + ", userlastname=" + userlastname + ", userfirstname=" + userfirstname
				+ ", useremail=" + useremail + ", userpassword=" + userpassword + ", userstreetaddress="
				+ userstreetaddress + ", usercity=" + usercity + ", userstate=" + userstate + "]";
	}




//class closed
}